version: "3"

services:
  core:
    build:
      context: .
      dockerfile: DockerFile
    restart: always
    ports:
      - 80:8080
    container_name: be-core
    depends_on:
      - mysql
    networks:
      - pinkward
  mysql:
    image: mysql
    container_name: pinkward_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 3306:3306
    networks:
      - pinkward

networks:
  pinkward: