spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password:
    url: jdbc:mysql://mysql:3306/core?useSSL=false
server:
  port: 9000
---

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
  h2:
    console:
      enabled: true
